= Tensorflow for Java Example

This repository is a simple demo of using Tensorflow from Java.

== Running this codebase

. Check out code
. Run `./gradlew run`

Really, that's it.

== How that works

If you look at the `build.gradle`, it downloads tensorflow's jni and jar file and sets up your classpath.

== What I think of this

I think the build process is not much like what a java developer would expect.
It's better than it was pre 1.0.
If Tensorflow wants to help the java community embrace tensorflow, they must upload these artefacts to something like Bintray.
Also a gradle plugin would be nice.
It might be harder because there are a whole lot of flags that can be used during compilation that affect performance.
Currently my 4 year old laptop complains that I don't have certain flags enabled during compilation that could improve performance.

As of writing, the python API is very nice.
The java api is not there yet.
A good example is how a constant is created in my code right now.
You can see this in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java[their example] too.

**These observations are not complaints.
I know this is still ~~experimental~~ preview, and the Tensorflow developers are most likely going to solve these before making it public.**